input {
  jdbc {
    jdbc_connection_string => "jdbc:sqlserver://sqlserver:1433;databaseName=logdb;"
    jdbc_user => "sa"
    jdbc_password => "P@ssw0rd"
    jdbc_driver_library => "/usr/share/logstash/config/mssql-jdbc-9.2.1.jre8.jar"
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"

    statement => "SELECT * FROM patients WHERE id > :sql_last_value ORDER BY id ASC"
    use_column_value => true
    tracking_column => "id"
    tracking_column_type => "numeric"
    last_run_metadata_path => "/usr/share/logstash/config/.logstash_jdbc_last_run"

    schedule => "*/30 * * * * *"  # every 30 seconds
  }
}

filter {
  mutate {
    rename => { "first_name"      => "[patient][first_name]" }
    rename => { "last_name"       => "[patient][last_name]"  }
    rename => { "age"             => "[patient][age]"        }
    rename => { "gender"          => "[patient][gender]"     }
    rename => { "admission_date"  => "[patient][admission_date]" }
    rename => { "id"              => "[patient][id]"         }
  }
}

output {
  elasticsearch {
    hosts => ["https://es01:9200"]
    ssl_enabled => true
    ssl_verification_mode => "full"
    ssl_certificate_authorities => "/usr/share/logstash/config/rootCA.pem"
    #cacert => "/usr/share/logstash/config/rootCA.pem"
    user => "elastic"
    password => "Faiziraja143@f"
  index => "patients"
#    document_id => "%{[patient][id]}"
  }

  stdout { codec => rubydebug }
}
